### ISSUE TITLE
socat version

### ISSUE THREAD

**Issue by sjanahan** [davedoesdev/cp-remote#1]
So when I tried to configure this initially, I downloaded the newest version of socat(2.0.0-b7.tar.gz). It didn't play well with the FD syntax in the shell script.

Version 1.7.1.3 worked fine with the rest of the code. Just a heads up!

Dave was super helpful in helping me find this issue.

**Comment by davedoesdev** [comment]
I'm going to report the underlying issue to the socat author. On 1.7.x, the following works:

socat FD:0 FD:1

but on 2.0.0 nothing happens when you type into standard input, even after a newline.

**Comment by davedoesdev** [comment]
Works with socat 2.0.0-b9
